Lock: False
channalId: -1001741448769
desc: 'music from @biliaudiobot'
botToken: '571xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx5sYu8ZI'
#when you select lock:true,you must use aes to encode all Token! And Dont push your token to github directly.

onedrive: {statu: Fasle, target: authkey/onedrive.token}
search: { statu: False,
          data:
            { duration: '1', keyword: ASOUL 原创曲, order: pubdate, page: '1', search_type: video,  tids_1: '3', tids_2: '28' }
}
RSS : {statu: Fasle, RssAddressToken: 'https://rssxxxxxxxxxxxxxxxxx'}
DataCallback : {statu: False, UserIdToken: 'bxxxxxxxxxx79'}
ClientBot :  {statu: False, owner: '527xxxxxx445'}